language: cpp
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get upgrade -qq -y
 - sudo apt-get install -qq -y unixodbc-dev libmysqlclient-dev
script: ./configure & make -s

